### ISSUE TITLE
Support SHACL severity indicators

### ISSUE THREAD

**Issue by elichad** [eScienceLab/rocrate-validator#5]
See https://www.w3.org/TR/shacl/#severity

> The specific values of sh:severity have no impact on the validation, but MAY be used by user interface tools to categorize validation results. The values of sh:severity are used by SHACL processors to populate the sh:resultSeverity field of validation results, see [section on severity in validation results](https://www.w3.org/TR/shacl/#results-severity). Any IRI can be used as a severity.

This would be an alternative to the existing method of using the folder structure to indicate severity (`may/`, `must/`, and `should/` folders within a profile)

**Comment by stain** [comment]
@OliverWoolland voluntered to look into LinkML code to make it propagate this through to SHACL.

**Comment by elichad** [comment]
This has been implemented by the CRS4 team 🙌 
Implementation: https://github.com/crs4/rocrate-validator/pull/8
Guidance for LinkML annotations to pass through to SHACL: https://github.com/crs4/rocrate-validator/issues/2#issuecomment-2360227158
